# Site settings
title: m0gg it up
email: marcel@m0gg.org
description: > # this means to ignore newlines until "baseurl:"
  I'll just try to show the awesome things i'm working on!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://m0gg.github.io/" # the base hostname & protocol for your site
twitter_username:
github_username:  m0gg

# Build settings
markdown: kramdown
